import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lets build facebook clone</h1>

      {/* Header */}

      {/* Body */}
      <div>
        {/* Sidebar */}
        {/* Feed */}
        {/* Widgets */}
      </div>
    </div>
  );
}
